# .github/workflows/build.yml

name: Core Kernel Build Logic

on:
  workflow_call:

# Ortam değişkenlerini burada tanımlıyoruz
env:
  # Hedef Kernel Bilgileri
  ANDROID_VERSION: "android14"
  KERNEL_VERSION: "6.1"
  SUB_LEVEL: "134"
  OS_PATCH_LEVEL: "2025-05"
  
  # KernelSU varyantı ve branch'ı
  KERNELSU_VARIANT: "NEXT" # Sadece NEXT derliyoruz
  KERNELSU_BRANCH: "main"   # KernelSU-Next'in ana branch'ını kullanıyoruz

jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      # 1. Derleme ortamını ve gerekli araçları kur
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3
      
      # 2. Derleyiciyi (Toolchain) indir
      - name: Download Toolchain
        run: git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.git toolchain

      # 3. GKI kaynak kodunu indir
      - name: Checkout GKI Source
        run: git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }} kernel

      # 4. KernelSU kaynak kodunu kernel ağacına dahil et
      - name: Integrate KernelSU
        run: |
          cd kernel
          git clone --depth=1 https://github.com/KernelSU-Next/KernelSU-Next.git -b ${{ env.KERNELSU_BRANCH }} KernelSU
          cd ..

      # 5. KENDİ ÖZEL İMZANI KERNEL'E GÖM
      - name: Patch Custom Signature
        run: |
          echo "Patching KernelSU with hardcoded signature..."
          SIGNATURE_FILE="kernel/KernelSU/include/ksu_signature.h"
          
          # -------------------- ❗❗ ÖNEMLİ DEĞİŞİKLİK BURADA ❗❗ --------------------
          # Kendi HASH'inizi aşağıdaki tırnak işaretlerinin arasına YAPIŞTIRIN!
          echo '#define SIGNATURE_RAW "BURAYA_KENDİ_EŞSİZ_İMZA_HASHİNİZİ_YAPIŞTIRIN"' > $SIGNATURE_FILE
          # --------------------------------------------------------------------------

          echo "Signature file content:"
          cat $SIGNATURE_FILE

      # 6. Kerneli derle
      - name: Build Kernel
        run: |
          cd kernel
          export PATH="$GITHUB_WORKSPACE/toolchain/bin:$PATH"
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make O=out gki_defconfig
          make O=out -j$(nproc --all)
          cd ..

      # 7. Derlenen dosyaları paketle ve artifact olarak kaydet
      - name: Package and Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KERNELSU_VARIANT }}-${{ env.SUB_LEVEL }}-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.${{ env.OS_PATCH_LEVEL }}-boot
          path: kernel/out/arch/arm64/boot/Image.gz
